version: "3.3"
services:
# サービス名はdevcontainer.jsonのファイル内と一致させる
  kayaport:
    build:
      context: .
      dockerfile: ./.devcontainer/Dockerfile
    ports:
      - "80:80"
      - "11075:11072"
    image: kayaport-i1
    init: true
    container_name: kayaport-c1
    hostname: kayaport1
    stdin_open: true
    tty: true

